from enum import Enum


class StatusDenuncia(str, Enum):
    REGISTRADA = "REGISTRADA"
    EM_ANALISE = "EM_ANALISE"
    ENCAMINHADA = "ENCAMINHADA"
    EM_ANDAMENTO = "EM_ANDAMENTO"
    RESOLVIDA = "RESOLVIDA"
    ARQUIVADA = "ARQUIVADA"
