from enum import Enum


class TipoArquiteturaHostil(str, Enum):
    BANCO_DIVIDO = "BANCO_DIVIDO"
    ESPIGAO_METALICO = "ESPIGAO_METALICO"
    INCLINACAO_DE_SUPERFICIE = "INCLINACAO_DE_SUPERFICIE"
    RETIRADA_DE_ASSENTO = "RETIRADA_DE_ASSENTO"
    BARREIRA_FISICA = "BARREIRA_FISICA"
    EMISSAO_SONORA = "EMISSAO_SONORA"
    ASPERSOR_DE_AGUA = "ASPERSOR_DE_AGUA"
    OUTRO = "OUTRO"
