from enum import Enum


class TipoEnum(Enum):
    OBSTACULO_FISICO = 'OBSTACULO_FISICO'
    IMPEDIMENTO_ASSENTO = 'IMPEDIMENTO_ASSENTO'
    IMPEDIMENTO_ABRIGO = 'IMPEDIMENTO_ABRIGO'
    RESTRICAO_ACESSO = 'RESTRICAO_ACESSO'
